Repository jupyterhub/binderhub, pull requests merged in 2020-11, with the labels that each got.

#1190 pin kubernetes, jupyterhub in requirements.in
  helm-chart/images/binderhub/requirements.in
  helm-chart/images/binderhub/requirements.txt
Labels: dependencies, maintenance

#1189 Improve debugging of health-check failures
  binderhub/health.py
  binderhub/log.py
Labels: maintenance

#1188 CI / Local dev refresh and Helm2->3 transition
  .gitattributes
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  binderhub/tests/conftest.py
  binderhub/tests/test_auth.py
  ci/common
  ci/install.sh
  ci/publish
  ci/test-auth
  ci/test-helm
  ci/test-main
  dev-requirements.txt
  doc/zero-to-binderhub/setup-prerequisites.rst
  helm-chart/chartpress.yaml
  helm-chart/minikube-binder.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml
  testing/local-binder-k8s-hub/binderhub_config.py
  testing/local-binder-k8s-hub/binderhub_config_auth_additions.py
  testing/local-binder-k8s-hub/install-jupyterhub-chart
  testing/local-binder-k8s-hub/jupyterhub-chart-config-auth-additions.yaml
  testing/local-binder-k8s-hub/jupyterhub-chart-config.yaml
  testing/local-binder-mocked-hub/binderhub_config.py
  testing/localonly/binderhub_config.py
  testing/minikube/binderhub_auth_config.py
  testing/minikube/binderhub_config.py
  testing/minikube/install-hub
  testing/minikube/jupyterhub-helm-config.yaml
Labels: documentation, maintenance

#1198 Reduce logging to help readability in CI
  .travis.yml
Labels: maintenance

#1197 Document the chartpress Helm chart publishing commit message
  ci/publish
Labels: maintenance

#1201 CI: stop asserting local binderhub version match remote version
  binderhub/tests/test_main.py
Labels: maintenance

#1196 Update v1beta to v1 in rbac resources
  helm-chart/binderhub/templates/rbac.yaml
Labels: maintenance

#1203 CI: missed version assertion, retain both with sufficient flex
  binderhub/tests/test_main.py
Labels: maintenance

#1212 Syntax error fix to publishing workflow
  .github/workflows/publish.yml
  .github/workflows/test.yml
  ci/common
Labels: maintenance

#1205 [MRG] Replace gen.coroutine/yeild with modern async/await
  binderhub/registry.py
  binderhub/repoproviders.py
Labels: maintenance

#1215 [MRG] GitHub actions badge in README
  README.md
  README.rst
  setup.py
Labels: maintenance
