Repository jupyterhub/binderhub, pull requests merged in 2020-10, with the labels that each got.

#1157 Enable CodeQL code scanning as a GitHub Action
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#1166 Generalise k8s setup instructions in z2bh guide
  doc/zero-to-binderhub/setup-prerequisites.rst
Labels: documentation

#1183 CI: Bump Minikube and document publishing
  .travis.yml
  ci/publish-id_rsa.enc
  ci/test-helm
Labels: maintenance

#1182 CI: Test using Node 14 - now an active LTS release
  .travis.yml
Labels: maintenance

#1185 CI: avoid warnings registering custom markers with pytest
  binderhub/tests/conftest.py
Labels: maintenance

#1181 Remove no longer used doc/environment.yml
  doc/environment.yml
Labels: maintenance

#1096 Add podAnnotations config for the binder deployment - will enable checksum change based restarts
  helm-chart/binderhub/templates/deployment.yaml
  helm-chart/binderhub/values.yaml
Labels: enhancement

#1180 Dependency freezer script, bumped image deps, and doc-requirements.txt cleanup
  dev-requirements.txt
  doc/conf.py
  doc/doc-requirements.txt
  helm-chart/images/binderhub/Dockerfile
  helm-chart/images/binderhub/dependencies
  helm-chart/images/binderhub/requirements.in
  helm-chart/images/binderhub/requirements.txt
  requirements.txt
Labels: maintenance
