Repository jupyterhub/binderhub, pull requests merged in 2021-07, with the labels that each got.

#1324 Add docstrings for Build object
  binderhub/build.py
Labels: documentation

#1330 Bump Chart.yaml apiVersion (embeds requirements.yaml content into Chart.yaml)
  CONTRIBUTING.md
  doc/debug.rst
  helm-chart/binderhub/Chart.yaml
  helm-chart/binderhub/requirements.yaml
  testing/local-binder-k8s-hub/install-jupyterhub-chart
Labels: maintenance

#1331 Add schema.yaml for helm3 compliant chart validation
  .github/workflows/publish.yml
  .github/workflows/test.yml
  dev-requirements.txt
  helm-chart/.gitignore
  helm-chart/binderhub/.helmignore
  helm-chart/binderhub/schema.yaml
  helm-chart/binderhub/templates/deployment.yaml
  helm-chart/binderhub/templates/secret.yaml
  helm-chart/binderhub/values.yaml
  tools/generate-json-schema.py
  tools/templates/lint-and-validate-values.yaml
  tools/validate-against-schema.py
Labels: enhancement

#1339 ci: fix publish workflow by adding missing dependency
  .github/workflows/publish.yml
  dev-requirements.txt
Labels: ci

#1337 Let z2jh seed jupyterhub.hub.services.binder.apiToken
  doc/zero-to-binderhub/setup-binderhub.rst
  helm-chart/binderhub/templates/deployment.yaml
  helm-chart/binderhub/templates/secret.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml
  testing/local-binder-k8s-hub/jupyterhub-chart-config.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: enhancement
