Repository jupyterhub/binderhub, pull requests merged in 2022-10, with the labels that each got.

#1535 binderhub image: refactor with pip cache, and tini from apt
  .github/workflows/test.yml
  helm-chart/images/binderhub/Dockerfile
Labels: maintenance

#1536 Add automation to refreeze and update google-cloud-logging from v1 to v3
  .github/workflows/watch-dependencies.yaml
  ci/refreeze
  helm-chart/images/binderhub/README.md
  helm-chart/images/binderhub/requirements.in
  helm-chart/images/binderhub/requirements.txt
Labels: maintenance

#1530 Update https.rst
  doc/https.rst
Labels: documentation

#1526 Move pod quota checking into separate class
  binderhub/app.py
  binderhub/builder.py
  binderhub/quota.py
  binderhub/tests/test_quota.py
  testing/local-binder-local-hub/binderhub_config.py
Labels: maintenance

#1550 ci: test k3s 1.24
  .github/workflows/test.yml
Labels: maintenance

#1552 fix default value for launch_quota_class
  binderhub/app.py
Labels: bug

#1551 add timeout to tests
  binderhub/tests/test_build.py
  dev-requirements.txt
  pyproject.toml
Labels: maintenance

#1544 Update to z2jh 2 and JupyterHub 3
  .github/workflows/test.yml
  doc/authentication.rst
  helm-chart/binderhub/Chart.yaml
  helm-chart/binderhub/templates/deployment.yaml
  helm-chart/binderhub/values.yaml
  helm-chart/images/binderhub/requirements.in
  helm-chart/images/binderhub/requirements.txt
  testing/local-binder-k8s-hub/binderhub_config_auth_additions.py
  testing/local-binder-k8s-hub/jupyterhub-chart-config-auth-additions.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: maintenance, breaking

#1543 Change component name from dind to image-builder
  binderhub/build.py
  binderhub/tests/test_build.py
  helm-chart/binderhub/templates/dind/daemonset.yaml
Labels: maintenance
