Repository jupyterhub/binderhub, pull requests merged in 2022-12, with the labels that each got.

#1531 Podman in k8s
  .github/workflows/test.yml
  .github/workflows/watch-dependencies.yaml
  binderhub/build.py
  binderhub/tests/test_build.py
  docs/source/zero-to-binderhub/setup-binderhub.rst
  helm-chart/binderhub/files/binderhub_config.py
  helm-chart/binderhub/schema.yaml
  helm-chart/binderhub/templates/NOTES.txt
  helm-chart/binderhub/templates/container-builder/daemonset.yaml
  helm-chart/binderhub/templates/dind/daemonset.yaml
  helm-chart/binderhub/templates/image-cleaner.yaml
  helm-chart/binderhub/templates/secret.yaml
  helm-chart/binderhub/values.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking, new

#1587 binderhub-chart-config-old.yaml `imageBuilderType: "local"`
  testing/k8s-binder-k8s-hub/binderhub-chart-config-old.yaml
Labels: ci

#1586 Add compatibility for fetching tokens from other Docker registries
  binderhub/registry.py
  binderhub/tests/test_registry.py
Labels: enhancement

#1589 Add tolerations to binderhub
  helm-chart/binderhub/schema.yaml
  helm-chart/binderhub/templates/deployment.yaml
  helm-chart/binderhub/values.yaml
Labels: enhancement

#1591 Bump repo2docker to 2022.10.0
  binderhub/app.py
  binderhub/build.py
Labels: maintenance

#1588 Simplify image-cleaner handling
  helm-chart/binderhub/schema.yaml
  helm-chart/binderhub/templates/NOTES.txt
  helm-chart/binderhub/templates/container-builder/daemonset.yaml
  helm-chart/binderhub/templates/image-cleaner.yaml
  helm-chart/binderhub/values.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml
  tools/templates/lint-and-validate-values.yaml
Labels: breaking

#1592 Warn about build_docker_config being a Helm Chart option not a BinderHub option
  binderhub/app.py
Labels: maintenance

#1593 Add breaking changes to CHANGES.md
  CHANGES.md
Labels: documentation

#1597 Fix the default `use_registry` value
  helm-chart/binderhub/values.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart-config-old.yaml
Labels: bug

#1598 Add `health_handler_class` to make `/health` handler is customisable
  binderhub/app.py
  binderhub/health.py
Labels: new

#1599 Fix auth docs config (again)
  docs/source/authentication.rst
Labels: documentation

#1601 pink.daemonset.extraArgs[]
  helm-chart/binderhub/schema.yaml
  helm-chart/binderhub/templates/container-builder/daemonset.yaml
Labels: enhancement

#1603 Add all `c.BinderHub.*` properties used in chart to Values.yaml
  helm-chart/binderhub/templates/container-builder/daemonset.yaml
  helm-chart/binderhub/templates/deployment.yaml
  helm-chart/binderhub/values.yaml
Labels: maintenance

#1602 Test dind and pink
  .github/workflows/test.yml
  testing/k8s-binder-k8s-hub/binderhub-chart+dind.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart+pink.yaml
  testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml
  testing/k8s-binder-k8s-hub/cm-insecure-registries-dind.yaml
  testing/k8s-binder-k8s-hub/cm-insecure-registries-pink.yaml
Labels: ci
