Repository jupyterhub/binderhub, pull requests merged in 2023-10, with the labels that each got.

#1756 Z2JH 3.1.0
  helm-chart/binderhub/Chart.yaml
Labels: enhancement

#1755 Revert "Use URLSearchParams() to construct query strings"
  js/packages/binderhub-client/lib/index.js
Labels: bug

#1758 JS: Add unit tests (with coverage) & use `URL` object instead of strings to construct some URLs
  .eslintrc.js
  .github/workflows/jest.yml
  binderhub/static/js/index.js
  binderhub/static/js/src/favicon.js
  binderhub/static/js/src/favicon.test.js
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/lib/index.test.js
  package.json
Labels: tests, maintenance, code:html/js/css, code:js-binderhub-client

#1766 Add `BuildExecutor.repo2docker_extra_args` config
  binderhub/build.py
  binderhub/tests/test_build.py
Labels: new

#1761 Split big index.js file into multiple smaller files
  binderhub/static/js/index.js
  binderhub/static/js/src/constants.js
  binderhub/static/js/src/form.js
  binderhub/static/js/src/log.js
  binderhub/static/js/src/repo.js
  binderhub/static/js/src/urls.js
Labels: maintenance, code:html/js/css

#1768 Make eslint understand modern .js with babel's parser
  .eslintrc.js
  package.json
Labels: maintenance, code:html/js/css

#1770 pre-commit: let prettier autoformat .css files
  .pre-commit-config.yaml
  binderhub/static/index.css
  binderhub/static/loading.css
  docs/source/_static/custom.css
Labels: maintenance, code:html/js/css

#1771 JS: Remove dead state transition validation code
  binderhub/static/js/index.js
  js/packages/binderhub-client/lib/index.js
Labels: maintenance, code:html/js/css, code:js-binderhub-client

#1772 JS: fix duplicate line typo
  binderhub/static/js/index.js
Labels: maintenance, code:html/js/css

#1769 pre-commit: let prettier format .js files
  .eslintrc.js
  .pre-commit-config.yaml
  binderhub/static/js/index.js
  binderhub/static/js/src/badge.js
  binderhub/static/js/src/constants.js
  binderhub/static/js/src/favicon.js
  binderhub/static/js/src/favicon.test.js
  binderhub/static/js/src/form.js
  binderhub/static/js/src/loading.js
  binderhub/static/js/src/log.js
  binderhub/static/js/src/repo.js
  binderhub/static/js/src/urls.js
  examples/appendix/static/custom.js
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/lib/index.test.js
  webpack.config.js
Labels: maintenance, code:html/js/css, code:js-binderhub-client

#1647 Allow building the image without needing to launch it
  binderhub/app.py
  binderhub/builder.py
  binderhub/tests/conftest.py
  binderhub/tests/test_auth.py
  binderhub/tests/test_build.py
  examples/binder-api.py
  testing/local-binder-mocked-hub/binderhub_config.py
Labels: new

#1773 JS: Use async generator instead of callbacks + add tests
  binderhub/static/js/index.js
  binderhub/templates/index.html
  binderhub/templates/loading.html
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/package.json
  js/packages/binderhub-client/tests/fixtures/fullbuild.eventsource
  js/packages/binderhub-client/tests/index.test.js
  js/packages/binderhub-client/tests/utils.js
Labels: maintenance, code:html/js/css, code:js-binderhub-client

#1775 JS: Add more inline documentation comments
  binderhub/static/js/src/badge.js
  binderhub/static/js/src/constants.js
  binderhub/static/js/src/form.js
  binderhub/static/js/src/loading.js
  binderhub/static/js/src/log.js
  binderhub/static/js/src/repo.js
  binderhub/static/js/src/urls.js
Labels: documentation, code:html/js/css, code:js-binderhub-client

#1742 Allow passing buildOnly param to the server from the js client
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/tests/index.test.js
Labels: maintenance, code:js-binderhub-client

#1774 Do not escape query included in url launch parameter
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/tests/index.test.js
Labels: bug

#1777 Add missing file paths to chartpress monitored paths
  helm-chart/chartpress.yaml
Labels: bug, ci

#1778 JS: Refactor link & badge generation, use URLs (not string) for base URLs
  binderhub/static/js/index.js
  binderhub/static/js/src/badge.js
  binderhub/static/js/src/constants.js
  binderhub/static/js/src/favicon.js
  binderhub/static/js/src/repo.js
  binderhub/static/js/src/urls.js
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/tests/index.test.js
Labels: tests, code:html/js/css, code:js-binderhub-client

#1779 Guarantee that badge_base_url will always have a trailing /
  binderhub/base.py
  binderhub/static/js/src/constants.js
Labels: bug, code:python, code:html/js/css

#1784 Kill singleuser test servers to reduce k3s resource usage
  binderhub/tests/test_build.py
Labels: ci

#1783 JS: Fix some JSDoc types, and misc details in tests
  js/packages/binderhub-client/lib/index.js
  js/packages/binderhub-client/tests/index.test.js
  js/packages/binderhub-client/tests/utils.js
Labels: maintenance, code:js-binderhub-client

#1782 JS: Ensure all variables are camelCased
  binderhub/static/js/src/loading.js
  binderhub/static/js/src/repo.js
Labels: maintenance, code:html/js/css

#1786 ci: test against k8s 1.28
  .github/workflows/test.yml
Labels: ci

#1781 JS: Remove all references to global URL constants
  binderhub/static/js/index.js
  binderhub/static/js/src/constants.js
  binderhub/static/js/src/repo.js
Labels: maintenance, code:html/js/css

#1789 Move to quay.io
  .github/workflows/publish.yml
  helm-chart/binderhub/values.yaml
  helm-chart/chartpress.yaml
  helm-chart/images/binderhub/Dockerfile
Labels: maintenance, breaking
