Repository jupyterhub/binderhub, pull requests merged in 2023-05, with the labels that each got.

#1684 k3s latest: specify version (v1.26)
  .github/workflows/test.yml
Labels: ci

#1683 launch_quota.total_quota
  .github/workflows/test.yml
  binderhub/health.py
Labels: bug

#1693 Add simple README for @jupyterhub/binderhub-client
  js/packages/binderhub-client/README.md
Labels: documentation

#1702 maint: fix broken test by upgrading to non-deprecated ruamel.yaml syntax
  helm-chart/binderhub/values.yaml
  testing/local-binder-k8s-hub/install-jupyterhub-chart
Labels: maintenance

#1711 maint: fix ruamel.yaml issue, flush needed now but not before
  ci/check_embedded_chart_code.py
  dev-requirements.txt
  helm-chart/binderhub/files/binderhub_config.py
  helm-chart/images/binderhub/requirements.txt
  testing/local-binder-k8s-hub/install-jupyterhub-chart
  tools/generate-json-schema.py
  tools/validate-against-schema.py
Labels: maintenance

#1708 Fix homepage url in binderhub-client's package.json
  js/packages/binderhub-client/package.json
Labels: documentation

#1709 refactor: pytest/coverage config to pyproject.toml, set --maxfail to 2
  .coveragerc
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance
