Repository jupyterhub/binderhub, pull requests merged in 2023-04, with the labels that each got.

#1651 dependabot: monthly updates of github actions
  .github/dependabot.yaml
Labels: maintenance

#1653 maint: build javascript w. node 18, docs with pyhon 3.11, test with python 3.11
  .github/workflows/test.yml
  .readthedocs.yaml
  helm-chart/images/binderhub/Dockerfile
Labels: maintenance

#1655 maint: bump xterm and xterm-addon-fit
  package.json
Labels: maintenance, code:html/js/css

#1659 maint: Prompt check of public repo during ref resolution
  binderhub/builder.py
Labels: maintenance

#1648 maint: refactoring around pycurl as an optional dependency
  .github/workflows/test.yml
  dev-requirements.txt
  docs/source/contribute.md
  helm-chart/images/binderhub/Dockerfile
  helm-chart/images/binderhub/requirements.in
  helm-chart/images/binderhub/requirements.txt
  requirements.txt
  setup.py
Labels: maintenance

#1662 catch errors before caching in binderhub health check
  binderhub/health.py
Labels: bug

#1663 fix image name for docker registry health check
  binderhub/health.py
Labels: bug

#1665 ci: fix watch-dependencies workflow so it bumps docker and podman images
  .github/workflows/watch-dependencies.yaml
  helm-chart/binderhub/values.yaml
Labels: ci

#1675 ci: run watch dependencies once a month, limit to main branch pushes
  .github/workflows/watch-dependencies.yaml
Labels: ci
