Repository jupyterhub/binderhub, pull requests merged in 2023-01, with the labels that each got.

#1610 breaking: require Python 3.8, from Python 3.6
  .pre-commit-config.yaml
  helm-chart/binderhub/files/binderhub_config.py
  pyproject.toml
  setup.py
Labels: maintenance, breaking

#1612 ci: set GITHUB_ACCESS_TOKEN to temporary read only token
  .github/workflows/test.yml
  binderhub/tests/conftest.py
  binderhub/tests/http-record.api.github.com.gists.json
  binderhub/tests/http-record.api.github.com.json
  binderhub/tests/test_repoproviders.py
Labels: ci

#1615 ci: fix changed resolved ref for dataverse test, fix recent github ratelimit PR
  binderhub/tests/conftest.py
  binderhub/tests/test_repoproviders.py
Labels: ci

#1521 Breaking: Default to traitlets based Build class
  CHANGES.md
  binderhub/app.py
  binderhub/base.py
  binderhub/build.py
  binderhub/build_local.py
  binderhub/builder.py
  binderhub/health.py
  binderhub/tests/test_build.py
  binderhub/tests/test_main.py
  helm-chart/binderhub/values.yaml
  testing/local-binder-local-hub/binderhub_config.py
Labels: enhancement, breaking

#1611 breaking: test and use Python 3.11 in Helm chart image, up from Python 3.9
  .github/workflows/diff.yml
  .github/workflows/publish.yml
  .github/workflows/test-docker-build.yaml
  .github/workflows/test.yml
  .github/workflows/watch-dependencies.yaml
  ci/refreeze
  helm-chart/images/binderhub/Dockerfile
  helm-chart/images/binderhub/requirements.txt
Labels: breaking, code:helm-chart

#1609 breaking: require k8s 1.21 like z2jh does now
  .github/workflows/test.yml
  helm-chart/binderhub/Chart.yaml
  helm-chart/binderhub/schema.yaml
Labels: maintenance, breaking, code:helm-chart

#1516 Using escaped username in progress api call affecting launch of serve…
  binderhub/launcher.py
Labels: bug

#1618 Document breaking changes so far
  CHANGES.md
Labels: documentation

#1619 ci: Debug versions health metrics endpoints after CI tests
  .github/workflows/test.yml
Labels: ci

#1626 Build memory limits/requests should be `ByteSpecification`
  binderhub/build.py
  binderhub/tests/test_build.py
Labels: bug

#1627 Ensure `GITHUB_ACCESS_TOKEN` is passed to local binderhub
  testing/local-binder-local-hub/jupyterhub_config.py
Labels: ci
