Repository jupyterhub/binderhub, pull requests merged in 2025-08, with the labels that each got.

#1999 Add step to restore context used by docker
  docs/source/contribute.md
Labels: documentation

#2004 Z2JH 4.2.0, JupyterHub 5.3.0
  helm-chart/binderhub/Chart.yaml
  helm-chart/images/binderhub/requirements.in
  helm-chart/images/binderhub/requirements.txt
  requirements.txt
Labels: dependencies

#1978 Move the React components its own package
  binderhub/static/js/pages/HomePage.jsx
  binderhub/static/js/pages/LoadingPage.jsx
  js/packages/binderhub-client/lib/client.js
  js/packages/binderhub-client/lib/spec.js
  js/packages/binderhub-client/package.json
  js/packages/binderhub-client/tests/index.test.js
  js/packages/binderhub-react-components/README.md
  js/packages/binderhub-react-components/package.json
  js/packages/binderhub-react-components/src/BuilderLauncher.jsx
  js/packages/binderhub-react-components/src/ErrorPage.jsx
  js/packages/binderhub-react-components/src/FaviconUpdater.jsx
  js/packages/binderhub-react-components/src/HowItWorks.jsx
  js/packages/binderhub-react-components/src/LinkGenerator.jsx
  js/packages/binderhub-react-components/src/LoadingIndicator.css
  js/packages/binderhub-react-components/src/LoadingIndicator.jsx
  js/packages/binderhub-react-components/src/NBViewerIFrame.jsx
  js/packages/binderhub-react-components/src/Progress.jsx
  js/packages/binderhub-react-components/src/img/favicon/fail.ico
  js/packages/binderhub-react-components/src/img/favicon/progress.ico
  js/packages/binderhub-react-components/src/img/favicon/success.ico
  package.json
Labels: code:js-binderhub-client, code:js-binderhub-react-components
